// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// The web app's .env holds DATABASE_URL. Prisma stays at the repo root until
// it moves into packages/db (#20). Paths are relative to the repo root, where
// Prisma commands run.
config({ path: "apps/web/.env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm exec tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
